<?xml version="1.0"?>
<package format="2">
  <name>termium_java</name>
  <version>0.0.3</version>
  <description>Termium Java installation to avoid platform dependencies.</description>
  <author email="s.k.alldritt@gmail.com">Stuart Alldritt</author>
  <maintainer email="esteve@apache.org">Stuart Alldritt</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
