name: CI

on:
  push:
    branches: [jazzy]
  pull_request:
    branches: [jazzy]
    types: [opened, reopened, synchronize]

jobs:
  build_and_test_desktop:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Java
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openjdk-21-jre
    - name: Install libbenchmark-dev
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libbenchmark-dev
    - uses: ros-tooling/setup-ros@0.7.9
      with:
        required-ros-distributions: jazzy
    - uses: actions/checkout@v4.2.1
    - name: Setup workspace with VCS repo file
      run: |
        mkdir -p ros2_java_ws/src
        cd ros2_java_ws
        curl -sL file://${{ github.workspace }}/ros2_java_desktop.repos | vcs import src
        # Use checked out version of ros2_java
        rm -rf src/ros2-java/ros2_java
        ln --symbolic ${{ github.workspace }} src/ros2-java
    - name: Install dependencies
      run: |
        echo "No known dependencies yet!"
        sudo apt-get install libasio-dev libbenchmark-dev
    - name: Run Colcon Build
      run: |
        cd ros2_java_ws
        colcon build --event-handlers=console_direct+ --symlink-install --packages-up-to rosidl_generator_java_tests rosidl_generator_java rcljava_common rcljava
    - name: Run Colcon Test
      run: |
        cd ros2_java_ws
        source install/setup.bash
        colcon test --event-handlers=console_direct+ --packages-select rosidl_generator_java_tests rosidl_generator_java rcljava_common rcljava
        colcon test-result --verbose
  build_android:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Java
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openjdk-21-jre
    - name: Install SDKMan
      run: |
        curl -s "https://get.sdkman.io" | bash
    - name: Install Gradle 8.6
      run: |
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.6
    - uses: actions/checkout@v4.2.1
    - uses: ros-tooling/setup-ros@0.7.9
      with:
        required-ros-distributions: jazzy
    - name: Install colcon extensions for Gradle
      run: |
        sudo pip3 install git+https://github.com/colcon/colcon-gradle.git
        sudo pip3 install git+https://github.com/colcon/colcon-ros-gradle.git
    - name: Install Python3 dev
      run: |
        sudo apt-get install -y python3-dev
    - name: Setup workspace with VCS repo file
      run: |
        mkdir -p ros2_java_ws/src
        cd ros2_java_ws
        curl -sL file://${{ github.workspace }}/ros2_java_android.repos | vcs import src
        # Use checked out version of ros2_java
        rm -rf src/ros2-java/ros2_java
        ln --symbolic ${{ github.workspace }} src/ros2-java
    - name: Install Android NDK
      run: |
        cd ros2_java_ws
        colcon build --symlink-install --event-handlers=console_direct+ --packages-up-to android_ndk
    - name: Run Colcon Build
      run: |
        cd ros2_java_ws

        export PYTHON3_EXEC="$( which python3 )"
        export PYTHON3_LIBRARY="$( ${PYTHON3_EXEC} -c 'import os.path; from distutils import sysconfig; print(os.path.realpath(os.path.join(sysconfig.get_config_var("LIBPL"), sysconfig.get_config_var("LDLIBRARY"))))' )"
        export PYTHON3_INCLUDE_DIR="$( ${PYTHON3_EXEC} -c 'from distutils import sysconfig; print(sysconfig.get_config_var("INCLUDEPY"))' )"

        export ANDROID_ABI=x86_64
        export ANDROID_NATIVE_API_LEVEL=android-22
        export ANDROID_STL=c++_shared
        export ANDROID_HOME=${PWD}/install/android_ndk/android-sdk
        export ANDROID_SDK_ROOT=${ANDROID_HOME}
        export ANDROID_NDK=${ANDROID_HOME}/ndk/26.3.11579264

        colcon build \
          --metas src/ros2-java/ros2_java/colcon.android.meta \
          --symlink-install \
          --event-handlers console_cohesion+ \
          --packages-up-to rclandroid \
          --packages-ignore uncrustify_vendor rosidl_generator_py \
          --gradle-args \
          --debug --info -Pament.android_stl=${ANDROID_STL} -Pament.android_abi=${ANDROID_ABI} -Pament.android_ndk=${ANDROID_NDK} -Pament.android_variant=release \
          --cmake-args \
          -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
          -DANDROID_FUNCTION_LEVEL_LINKING=OFF \
          -DANDROID_NATIVE_API_LEVEL=${ANDROID_NATIVE_API_LEVEL} \
          -DANDROID_ABI=${ANDROID_ABI} \
          -DANDROID_NDK=${ANDROID_NDK} \
          -DANDROID_STL=${ANDROID_STL} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_FIND_ROOT_PATH="${PWD}/install" \
          -DPython3_EXECUTABLE=${PYTHON3_EXEC} \
          -DPython3_LIBRARY=${PYTHON3_LIBRARY} \
          -DPython3_INCLUDE_DIR=${PYTHON3_INCLUDE_DIR}
    - uses: actions/upload-artifact@v4
      with:
        name: ros-jazzy-aar-release
        path: ros2_java_ws/install/rclandroid/share/rclandroid/android/rclandroid-release.aar
    
